In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r'C:\Users\e.i.chapaev\Desktop\_ugng_pr\Covid-19_svodnye.csv')

In [53]:
clearing_df = df.copy()
clearing_df.drop(1, inplace= True)
clearing_df.drop(0, inplace= True)
clearing_df = clearing_df.drop('COVID-19 (1-переболевшие, 0-здоровые)', axis = 1)
clearing_df = clearing_df.drop('Unnamed: 1', axis = 1)
clearing_df

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
2,ж,Идиятова,800,3.9,1.7,0.126,23.1,23%,22%,21%,18%,22%,4.9,10%,21%,28%,20%,21%,0
3,м,Поторочин,516,7,4.9,0.162,25.5,24%,27%,15%,15%,18%,5,25%,15%,24%,14%,23%,0
4,ж,Гореева,450,7.6,6.6,0.096,25.6,21%,27%,16%,20%,15%,4.6,16%,15%,33%,13%,23%,0
5,м,Белан,936,4.6,1.7,0.168,30.5,23%,26%,15%,22%,14%,4.5,13%,15%,31%,14%,26%,0
6,м,Вахрушев,449,3.8,4.9,0.127,20.5,20%,24%,17%,20%,18%,4.7,23%,12%,23%,17%,27%,0
7,м,М 38,235,4.6,1.7,0.134,28.2,21%,24%,22%,17%,22%,4.5,31%,7%,25%,15%,22%,0
8,м,М 41,302,7.6,4.9,0.185,19.2,13%,26%,17%,22%,24%,5,9%,14%,30%,22%,26%,0
9,м,М 49,480,3.8,6.6,0.178,27.7,40%,16%,13%,17%,15%,4.8,17%,11%,32%,13%,27%,0
10,м,М 68,745,3.8,6.6,0.146,20.5,22%,17%,16%,22%,22%,4.9,11%,17%,22%,19%,32%,0
11,м,М 51,816,4.6,1.7,0.091,25.6,33%,21%,15%,15%,16%,4.5,12%,15%,20%,15%,37%,0
12,м,М 30,756,7,4.9,0.156,24.4,33%,19%,21%,15%,13%,4.7,6%,16%,25%,23%,30%,0
13,ж,Ж 44,846,7,6.6,0.136,23.1,22%,22%,21%,20%,15%,4.5,31%,9%,21%,14%,25%,0
14,м,М 53,961,4.6,4.9,0.2,20.5,50%,13%,10%,16%,11%,5.1,12%,16%,18%,19%,36%,0
15,ж,Саитбурханова,800,7.6,6.6,0.096,31.2,15%,22%,20%,25%,18%,6.3,21%,9%,24%,19%,26%,1
16,ж,Иванова,777,6.9,3.3,0.12,33.3,12%,20%,20%,20%,28%,9.1,17%,9%,29%,18%,27%,1
17,ж,Шубина,835,4,1.7,0.158,35.9,11%,22%,18%,27%,22%,7.6,16%,8%,29%,22%,27%,1
18,ж,Желдыдина,611,4.2,6.6,0.179,27.7,16%,29%,24%,15%,15%,8.5,22%,10%,24%,18%,25%,1
19,м,Килин,519,4.2,3.3,0.099,20.5,37%,19%,14%,13%,18%,8.3,18%,14%,17%,18%,33%,1
20,ж,Юдицкая,587,5.9,2.2,0.097,23.1,23%,19%,21%,17%,19%,6.9,13%,12%,16%,29%,30%,1
21,ж,Шиляева,566,5.6,4.9,0.081,19.2,32%,19%,17%,17%,15%,8.4,15%,11%,15%,28%,31%,1
22,ж,Кельдибенова,602,3.5,4.9,0.11,19.2,14%,27%,17%,20%,23%,6.2,10%,13%,16%,30%,30%,1
23,м,Кожевников,846,3.8,8.3,0.163,33.3,12%,23%,22%,18%,25%,7.1,12%,10%,17%,33%,28%,1
24,м,Авзалов,843,5.7,6.6,0.167,25.6,40%,18%,13%,12%,17%,5.8,13%,13%,19%,20%,35%,1
25,ж,Вахрушева,518,6.2,6.6,0.185,31.2,17%,29%,18%,19%,18%,7.3,16%,12%,23%,19%,30%,1
26,м,Субботин,759,4.3,4.9,0.188,19.2,28%,23%,15%,20%,14%,6.9,11%,14%,15%,34%,27%,1
27,ж,Мокарова,850,5.8,2.2,0.097,35.9,14%,21%,20%,21%,24%,6.1,16%,12%,22%,20%,30%,1
28,ж,Харалзина,581,4.4,1.1,0.072,17.9,17%,20%,21%,22%,20%,8.8,17%,9%,20%,22%,32%,1
29,ж,Сергеева,836,3.7,4.9,0.119,20.5,24%,18%,19%,23%,16%,7.9,22%,13%,18%,18%,29%,1
30,м,Рябов,802,3.7,6.6,0.133,31.7,17%,23%,21%,22%,17%,8.9,9%,15%,15%,32%,29%,1
31,ж,Невоструева,744,5.6,4.9,0.164,33.3,16%,26%,19%,19%,20%,8.5,11%,12%,24%,23%,30%,1
32,ж,Слотина,584,4.3,4.4,0.175,17.9,16%,30%,18%,15%,21%,5.6,18%,12%,31%,18%,21%,1
33,ж,Костюнина,739,3.2,2.2,0.099,19.2,27%,26%,20%,15%,13%,4.5,21%,9%,18%,20%,33%,1
34,м,Молдовин,883,4.2,1.7,0.11,35.8,11%,32%,20%,20%,18%,4.3,17%,9%,24%,22%,29%,1
35,ж,Крылова,815,3.9,4.9,0.107,19.2,44%,18%,12%,13%,14%,2.8,20%,13%,21%,18%,27%,1
36,ж,Алферова,741,3.9,3.3,0.098,30.7,18%,24%,21%,21%,16%,5.4,12%,11%,23%,31%,23%,1
37,ж,Павлова,625,3.8,4.9,0.128,19.2,15%,22%,20%,27%,17%,6.4,7%,13%,29%,19%,32%,1
38,м,Броян,437,4.2,8.3,0.188,20.5,12%,23%,24%,20%,21%,4.5,25%,10%,21%,22%,23%,1
39,м,Закиров,385,3.8,8.3,0.183,19.2,14%,24%,21%,19%,22%,9.1,7%,13%,15%,29%,36%,1
40,ж,Орлова,678,5.7,3.3,0.199,28.2,15%,24%,18%,23%,21%,7.4,21%,10%,19%,28%,22%,1
41,м,Вахитов,446,3.8,4.9,0.104,20.5,21%,23%,21%,16%,19%,5.3,12%,11%,18%,33%,26%,1
42,м,Шаихов,585,3.7,4.9,0.11,19.2,39%,15%,19%,14%,13%,7.7,7%,16%,21%,32%,24%,1
43,ж,Иванова,554,3.7,3.3,0.124,19.2,19%,22%,21%,17%,20%,5.4,7%,12%,26%,29%,26%,1
44,ж,Захарова,906,3.6,4.9,0.135,27.7,15%,24%,18%,19%,24%,7.8,6%,11%,15%,30%,37%,1
45,ж,Ширифуллина,802,4.5,3.3,0.179,17.9,28%,24%,17%,14%,18%,7.4,8%,14%,25%,23%,29%,1

In [54]:
sex = {'ж': 1, 'м': 2}
clearing_df['Unnamed: 2'] = clearing_df['Unnamed: 2'].replace(sex)
clearing_df

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
2,1,Идиятова,800,3.9,1.7,0.126,23.1,23%,22%,21%,18%,22%,4.9,10%,21%,28%,20%,21%,0
3,2,Поторочин,516,7,4.9,0.162,25.5,24%,27%,15%,15%,18%,5,25%,15%,24%,14%,23%,0
4,1,Гореева,450,7.6,6.6,0.096,25.6,21%,27%,16%,20%,15%,4.6,16%,15%,33%,13%,23%,0
5,2,Белан,936,4.6,1.7,0.168,30.5,23%,26%,15%,22%,14%,4.5,13%,15%,31%,14%,26%,0
6,2,Вахрушев,449,3.8,4.9,0.127,20.5,20%,24%,17%,20%,18%,4.7,23%,12%,23%,17%,27%,0
7,2,М 38,235,4.6,1.7,0.134,28.2,21%,24%,22%,17%,22%,4.5,31%,7%,25%,15%,22%,0
8,2,М 41,302,7.6,4.9,0.185,19.2,13%,26%,17%,22%,24%,5,9%,14%,30%,22%,26%,0
9,2,М 49,480,3.8,6.6,0.178,27.7,40%,16%,13%,17%,15%,4.8,17%,11%,32%,13%,27%,0
10,2,М 68,745,3.8,6.6,0.146,20.5,22%,17%,16%,22%,22%,4.9,11%,17%,22%,19%,32%,0
11,2,М 51,816,4.6,1.7,0.091,25.6,33%,21%,15%,15%,16%,4.5,12%,15%,20%,15%,37%,0
12,2,М 30,756,7,4.9,0.156,24.4,33%,19%,21%,15%,13%,4.7,6%,16%,25%,23%,30%,0
13,1,Ж 44,846,7,6.6,0.136,23.1,22%,22%,21%,20%,15%,4.5,31%,9%,21%,14%,25%,0
14,2,М 53,961,4.6,4.9,0.2,20.5,50%,13%,10%,16%,11%,5.1,12%,16%,18%,19%,36%,0
15,ж,Саитбурханова,800,7.6,6.6,0.096,31.2,15%,22%,20%,25%,18%,6.3,21%,9%,24%,19%,26%,1
16,1,Иванова,777,6.9,3.3,0.12,33.3,12%,20%,20%,20%,28%,9.1,17%,9%,29%,18%,27%,1
17,1,Шубина,835,4,1.7,0.158,35.9,11%,22%,18%,27%,22%,7.6,16%,8%,29%,22%,27%,1
18,1,Желдыдина,611,4.2,6.6,0.179,27.7,16%,29%,24%,15%,15%,8.5,22%,10%,24%,18%,25%,1
19,2,Килин,519,4.2,3.3,0.099,20.5,37%,19%,14%,13%,18%,8.3,18%,14%,17%,18%,33%,1
20,1,Юдицкая,587,5.9,2.2,0.097,23.1,23%,19%,21%,17%,19%,6.9,13%,12%,16%,29%,30%,1
21,1,Шиляева,566,5.6,4.9,0.081,19.2,32%,19%,17%,17%,15%,8.4,15%,11%,15%,28%,31%,1
22,1,Кельдибенова,602,3.5,4.9,0.11,19.2,14%,27%,17%,20%,23%,6.2,10%,13%,16%,30%,30%,1
23,2,Кожевников,846,3.8,8.3,0.163,33.3,12%,23%,22%,18%,25%,7.1,12%,10%,17%,33%,28%,1
24,2,Авзалов,843,5.7,6.6,0.167,25.6,40%,18%,13%,12%,17%,5.8,13%,13%,19%,20%,35%,1
25,1,Вахрушева,518,6.2,6.6,0.185,31.2,17%,29%,18%,19%,18%,7.3,16%,12%,23%,19%,30%,1
26,2,Субботин,759,4.3,4.9,0.188,19.2,28%,23%,15%,20%,14%,6.9,11%,14%,15%,34%,27%,1
27,1,Мокарова,850,5.8,2.2,0.097,35.9,14%,21%,20%,21%,24%,6.1,16%,12%,22%,20%,30%,1
28,1,Харалзина,581,4.4,1.1,0.072,17.9,17%,20%,21%,22%,20%,8.8,17%,9%,20%,22%,32%,1
29,1,Сергеева,836,3.7,4.9,0.119,20.5,24%,18%,19%,23%,16%,7.9,22%,13%,18%,18%,29%,1
30,2,Рябов,802,3.7,6.6,0.133,31.7,17%,23%,21%,22%,17%,8.9,9%,15%,15%,32%,29%,1
31,1,Невоструева,744,5.6,4.9,0.164,33.3,16%,26%,19%,19%,20%,8.5,11%,12%,24%,23%,30%,1
32,1,Слотина,584,4.3,4.4,0.175,17.9,16%,30%,18%,15%,21%,5.6,18%,12%,31%,18%,21%,1
33,1,Костюнина,739,3.2,2.2,0.099,19.2,27%,26%,20%,15%,13%,4.5,21%,9%,18%,20%,33%,1
34,2,Молдовин,883,4.2,1.7,0.11,35.8,11%,32%,20%,20%,18%,4.3,17%,9%,24%,22%,29%,1
35,1,Крылова,815,3.9,4.9,0.107,19.2,44%,18%,12%,13%,14%,2.8,20%,13%,21%,18%,27%,1
36,1,Алферова,741,3.9,3.3,0.098,30.7,18%,24%,21%,21%,16%,5.4,12%,11%,23%,31%,23%,1
37,1,Павлова,625,3.8,4.9,0.128,19.2,15%,22%,20%,27%,17%,6.4,7%,13%,29%,19%,32%,1
38,2,Броян,437,4.2,8.3,0.188,20.5,12%,23%,24%,20%,21%,4.5,25%,10%,21%,22%,23%,1
39,2,Закиров,385,3.8,8.3,0.183,19.2,14%,24%,21%,19%,22%,9.1,7%,13%,15%,29%,36%,1
40,1,Орлова,678,5.7,3.3,0.199,28.2,15%,24%,18%,23%,21%,7.4,21%,10%,19%,28%,22%,1
41,2,Вахитов,446,3.8,4.9,0.104,20.5,21%,23%,21%,16%,19%,5.3,12%,11%,18%,33%,26%,1
42,2,Шаихов,585,3.7,4.9,0.11,19.2,39%,15%,19%,14%,13%,7.7,7%,16%,21%,32%,24%,1
43,1,Иванова,554,3.7,3.3,0.124,19.2,19%,22%,21%,17%,20%,5.4,7%,12%,26%,29%,26%,1
44,1,Захарова,906,3.6,4.9,0.135,27.7,15%,24%,18%,19%,24%,7.8,6%,11%,15%,30%,37%,1
45,1,Ширифуллина,802,4.5,3.3,0.179,17.9,28%,24%,17%,14%,18%,7.4,8%,14%,25%,23%,29%,1